baseURL = 'https://ryanpodonnell1.github.io/'
languageCode = 'en-us'
title = 'Blog'
theme = 'hugo-theme-learn'


[params]
  githubUrl = "https://github.com/ryanpodonnell1"

[outputs]
home = [ "HTML", "RSS", "JSON"]

